add flag for running agent only mode
prometheus/consul_exporter pull request #283
Opened 2023-11-17 10:04 UTC by n-marton

in agent only mode, the exporter exposes information only about services registered on the local agent

this is useful for cases when one uses consul with acl system enabled, so some services might not make to catalog because the agent doesn't have permission to register them

it would be nice to have metrics from both sides for comparison

2023-12-11 16:57 UTC, SuperQ requested changes

2023-12-11 16:57 UTC, SuperQ commented on pkg/exporter/consul_exporter.go
> +	}
Minor style nit.
```suggestion
	ok := e.collectServicesMetric(ch)
	if !e.agentOnly {
		ok = e.collectPeersMetric(ch)
		ok = e.collectLeaderMetric(ch) && ok
		ok = e.collectNodesMetric(ch) && ok
		ok = e.collectMembersMetric(ch) && ok
		ok = e.collectMembersWanMetric(ch) && ok
		ok = e.collectHealthStateMetric(ch) && ok
		ok = e.collectKeyValues(ch) && ok
	}
```

2023-12-13 12:57 UTC, n-marton commented on pkg/exporter/consul_exporter.go
> +	}
makes sense

2023-12-25 10:43 UTC, SuperQ approved these changes
Thanks!

2023-12-25 10:43 UTC, merged